### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by MedicD** [psmitty7373/mcscop#22]
Probably my fault, but I'm getting this error:

me@ubuntu:~/mcscop$ node app.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1277:14)
    at listen (net.js:1313:10)
    at Server.listen (net.js:1409:5)
    at Object.<anonymous> (/home/medicd/mcscop/app.js:1383:6)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

**Comment by MedicD** [comment]
Sleep helped.
