### ISSUE TITLE
Docker Instructions are not Working

### ISSUE THREAD

**Issue by Deastrom** [psmitty7373/mcscop#24]
Had to make the following changes to the Dockerfile to get the build to work...
```diff
diff --git a/Dockerfile b/Dockerfile
index a162d73..584a770 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -17,10 +17,13 @@ RUN apt-get update -y \
    mysql-server \
    mysql-client \
    sudo \
+   gnupg \
+   gnupg2 \
+   gnupg1 \
    && rm -rf /var/lib/apt/lists/*

 RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
-RUN apt-get install nodejs
+RUN apt-get install -y nodejs
 COPY . /home/mcscop/
 RUN npm install -d
 RUN chmod +x /home/mcscop/entrypoint.sh
```

Then when I went to run it, I got the following...

```powershell
PS C:\Users\benja\gitrepos\mcscop> docker run --name mcscop --rm -p 3000:3000 mcscop
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint mcscop (5945fd1e8cd3bbbb49c89637e83c9c12692175df31db9b7ba6e0a314e8f3d79a): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:3000:tcp:172.17.0.3:3000: input/output error.
PS C:\Users\benja\gitrepos\mcscop>
```

This is on Windows 10 with Docker for Windows at its latest version of Version 18.03.1-ce-win65 (17513).

**Comment by nathanhicks** [comment]
Yeah the Dockerfile probably hasn't been updated in a year to keep up with all the changes.  

As far as the error about the userland proxy goes - Have you verified there's no endpoint security or application firewall interfering on that machine?  What does your `netstat -ano` output look like when you get this error?  What's your docker version?

**Comment by Deastrom** [comment]
It's docker for Windows running in Windows 10.  Version is in the OP.  I'm
able to publish ports for other images fine.... Well, I guess I haven't run
another image since the last update.  I'll give another image a shot to be
sure.

**Comment by Deastrom** [comment]
alright, yes, docker for windows was causing that error... now for a new one :)
```powershell
Error connecting to MySql server: { Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MariaDB client
    at Handshake.Sequence._packetToError (/home/mcscop/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/home/mcscop/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/home/mcscop/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/home/mcscop/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/mcscop/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/mcscop/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/home/mcscop/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/home/mcscop/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/home/mcscop/node_modules/mysql/lib/Connection.js:130:18)
    at Timeout.handleMySqlConnection [as _onTimeout] (/home/mcscop/app.js:73:16)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MariaDB client',
  sqlState: '08004',
  fatal: true }
```

**Comment by nathanhicks** [comment]
Try replacing `mysql-server` in the Dockerfile with `mariadb-server` and `mysql-client` with `mariadb`.  Let me know if that fixes it.  If it doesn't, I'll clone the repo and take a closer look.
